services:
  - type: web
    name: ourlegacy2
    runtime: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_SERVICE_KEY
        sync: false
      - key: SECRET_SALT
        sync: false
      - key: REDIS_URL
        sync: false
