services:
  - type: web
    name: ourlegacy2
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -k uvicorn.workers.UvicornWorker -w 1 --bind 0.0.0.0:$PORT app:asgi_app
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_SERVICE_KEY
        sync: false
      - key: SECRET_SALT
        sync: false
      - key: REDIS_URL
        sync: false
